# Questions to be Answered:

# Exploratory Analysis:

* What's the general churn rate in the data base?

* What demographic/spend caracteristics are more associated with churn?

* Is there any correlation between contract type and churn probability?

** Reading the DataBase

In [5]:
import pandas as pd

In [6]:
df= pd.read_csv('telecom_churn_data.csv')

In [7]:
df.head()

,cliente_id,idade,sexo,tempo_contrato_meses,servico_internet,tipo_contrato,valor_mensal,total_gasto,num_servicos,dependentes,fatura_online,seguro_dispositivo,suporte_tecnico,churn
0,C1000,56,Masculino,7,Fibra,Mensal,52.52,342.20,1,Não,Não,Não,Sim,Não
1,C1001,69,Masculino,9,Fibra,Mensal,23.93,228.02,2,Não,Sim,Não,Não,Sim
2,C1002,46,Feminino,48,Não tem,Mensal,47.20,2394.83,3,Sim,Sim,Não,Não,Não
3,C1003,32,Masculino,59,Não tem,Anual,20.64,1153.78,1,Não,Não,Sim,Sim,Não
4,C1004,60,Masculino,39,Fibra,Bianual,117.84,4401.51,4,Sim,Sim,Não,Não,Sim

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 14 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   cliente_id            1000 non-null   object
 1   idade                 1000 non-null   int64
 2   sexo                  1000 non-null   object
 3   tempo_contrato_meses  1000 non-null   int64
 4   servico_internet      1000 non-null   object
 5   tipo_contrato         1000 non-null   object
 6   valor_mensal          1000 non-null   float64
 7   total_gasto           1000 non-null   float64
 8   num_servicos          1000 non-null   int64
 9   dependentes           1000 non-null   object
 10  fatura_online         1000 non-null   object
 11  seguro_dispositivo    950 non-null    object
 12  suporte_tecnico       950 non-null    object
 13  churn                 1000 non-null   object
dtypes: float64(2), int64(3), object(9)
memory usage: 109.5+ KB

In [9]:
df.churn.describe()

count     1000
unique       2
top        Não
freq       691
Name: churn, dtype: object

In [10]:
round(df['churn'].value_counts(normalize=True).mul(100),2)

churn
Não    69.1
Sim    30.9
Name: proportion, dtype: float64

### General Churn Rate in Data Base is 30,90%

In [12]:
import seaborn as sns

In [13]:
df[df['churn'] == 'Sim'].describe()

,idade,tempo_contrato_meses,valor_mensal,total_gasto,num_servicos
count,309.000000,309.000000,309.000000,309.000000,309.000000
mean,49.533981,35.265372,68.935631,2436.749547,2.540453
std,18.106547,21.096581,28.550364,1899.243256,1.151995
min,18.000000,1.000000,20.000000,27.830000,1.000000
25%,34.000000,17.000000,43.370000,975.370000,2.000000
50%,50.000000,34.000000,66.620000,1899.920000,2.000000
75%,65.000000,54.000000,93.500000,3616.780000,4.000000
max,79.000000,71.000000,119.770000,8024.560000,4.000000

In [14]:
df[df['churn'] == 'Não'].describe()

,idade,tempo_contrato_meses,valor_mensal,total_gasto,num_servicos
count,691.000000,691.000000,691.000000,691.000000,691.000000
mean,50.001447,34.088278,68.395919,2331.689349,2.476122
std,18.128966,19.968730,29.159818,1807.922813,1.116644
min,18.000000,1.000000,20.020000,25.540000,1.000000
25%,35.000000,17.000000,43.275000,909.665000,1.000000
50%,50.000000,33.000000,68.620000,1928.610000,2.000000
75%,66.000000,50.000000,92.955000,3332.330000,3.000000
max,79.000000,71.000000,119.690000,8650.900000,4.000000

### Not sure about caracteristics more realted to churn. The std of contract time,total spend and qnt of services are slightest lower in the 'No' churn table.

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 14 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   cliente_id            1000 non-null   object
 1   idade                 1000 non-null   int64
 2   sexo                  1000 non-null   object
 3   tempo_contrato_meses  1000 non-null   int64
 4   servico_internet      1000 non-null   object
 5   tipo_contrato         1000 non-null   object
 6   valor_mensal          1000 non-null   float64
 7   total_gasto           1000 non-null   float64
 8   num_servicos          1000 non-null   int64
 9   dependentes           1000 non-null   object
 10  fatura_online         1000 non-null   object
 11  seguro_dispositivo    950 non-null    object
 12  suporte_tecnico       950 non-null    object
 13  churn                 1000 non-null   object
dtypes: float64(2), int64(3), object(9)
memory usage: 109.5+ KB

In [17]:
(df[df['churn'] =='Sim'].groupby('tipo_contrato')['churn'].count()/df[df['churn'] =='Sim'].groupby('tipo_contrato')['churn'].count().sum()).mul(100)

tipo_contrato
Anual      28.155340
Bianual    11.326861
Mensal     60.517799
Name: churn, dtype: float64

### The churn ir greater in the Monthly payment type of customer 60,51% of total Churns

# Pré-processing:

* Outliers and Null values?

* How to treat categorical data?

### Filling the null values with data that is not gonna change the rate I've already got.

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 14 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   cliente_id            1000 non-null   object
 1   idade                 1000 non-null   int64
 2   sexo                  1000 non-null   object
 3   tempo_contrato_meses  1000 non-null   int64
 4   servico_internet      1000 non-null   object
 5   tipo_contrato         1000 non-null   object
 6   valor_mensal          1000 non-null   float64
 7   total_gasto           1000 non-null   float64
 8   num_servicos          1000 non-null   int64
 9   dependentes           1000 non-null   object
 10  fatura_online         1000 non-null   object
 11  seguro_dispositivo    950 non-null    object
 12  suporte_tecnico       950 non-null    object
 13  churn                 1000 non-null   object
dtypes: float64(2), int64(3), object(9)
memory usage: 109.5+ KB

In [23]:
df.seguro_dispositivo.value_counts(normalize=True).mul(100)

seguro_dispositivo
Não    58.631579
Sim    41.368421
Name: proportion, dtype: float64

In [24]:
import numpy as np

In [25]:
null_mask = df['seguro_dispositivo'].isnull()

In [26]:
fill_values = np.random.choice(
    ["Não", "Sim"], 
    size=null_mask.sum(),
    p=[0.6, 0.4])

In [27]:
df.loc[null_mask, 'seguro_dispositivo'] = fill_values

In [28]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 14 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   cliente_id            1000 non-null   object
 1   idade                 1000 non-null   int64
 2   sexo                  1000 non-null   object
 3   tempo_contrato_meses  1000 non-null   int64
 4   servico_internet      1000 non-null   object
 5   tipo_contrato         1000 non-null   object
 6   valor_mensal          1000 non-null   float64
 7   total_gasto           1000 non-null   float64
 8   num_servicos          1000 non-null   int64
 9   dependentes           1000 non-null   object
 10  fatura_online         1000 non-null   object
 11  seguro_dispositivo    1000 non-null   object
 12  suporte_tecnico       950 non-null    object
 13  churn                 1000 non-null   object
dtypes: float64(2), int64(3), object(9)
memory usage: 109.5+ KB

In [29]:
df.seguro_dispositivo.value_counts(normalize=True).mul(100)

seguro_dispositivo
Não    59.3
Sim    40.7
Name: proportion, dtype: float64

### Filled the missing values on device insurance by filling the missing values keeping the percentual of Yes and No about the same.

In [31]:
df.suporte_tecnico.value_counts(normalize=True).mul(100)

suporte_tecnico
Não    60.842105
Sim    39.157895
Name: proportion, dtype: float64

In [32]:
null_mask = df['suporte_tecnico'].isnull()

In [33]:
fill_values = np.random.choice(
    ["Não", "Sim"], 
    size=null_mask.sum(),
    p=[0.6084, 0.3916])

In [34]:
df.loc[null_mask, 'suporte_tecnico'] = fill_values

In [35]:
df.suporte_tecnico.value_counts(normalize=True).mul(100)

suporte_tecnico
Não    60.7
Sim    39.3
Name: proportion, dtype: float64

### Filled the missing values on thecnical suport by filling the missing values keeping the percentual of Yes and No about the same.

### Start changing cathegorical columns into dummies as a way to treat categorical columns

In [38]:
dfmodel = df

In [39]:
dfmodel.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 14 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   cliente_id            1000 non-null   object
 1   idade                 1000 non-null   int64
 2   sexo                  1000 non-null   object
 3   tempo_contrato_meses  1000 non-null   int64
 4   servico_internet      1000 non-null   object
 5   tipo_contrato         1000 non-null   object
 6   valor_mensal          1000 non-null   float64
 7   total_gasto           1000 non-null   float64
 8   num_servicos          1000 non-null   int64
 9   dependentes           1000 non-null   object
 10  fatura_online         1000 non-null   object
 11  seguro_dispositivo    1000 non-null   object
 12  suporte_tecnico       1000 non-null   object
 13  churn                 1000 non-null   object
dtypes: float64(2), int64(3), object(9)
memory usage: 109.5+ KB

In [40]:
dfmodel.servico_internet.value_counts()

servico_internet
Fibra      508
DSL        296
Não tem    196
Name: count, dtype: int64

In [41]:
dfinternet = pd.get_dummies(dfmodel.servico_internet).astype(int)

In [48]:
#dfinternet.drop(['Não tem'],axis=1,inplace=True).reset_index()

In [50]:
dfmodel = pd.concat([dfmodel,dfinternet],axis=1)

In [52]:
dfmodel.drop('servico_internet',axis=1,inplace=True)

In [54]:
df.tipo_contrato.value_counts()

tipo_contrato
Mensal     595
Anual      317
Bianual     88
Name: count, dtype: int64

In [56]:
dfcontratos = pd.get_dummies(df.tipo_contrato)

In [58]:
dfcontratos.drop('Mensal',axis=1,inplace=True)

In [60]:
dfmodel = pd.concat([dfmodel,dfcontratos],axis=1)

In [62]:
dfmodel.drop('tipo_contrato',axis=1,inplace=True)

In [64]:
dfdep = pd.get_dummies(dfmodel.dependentes,drop_first=True)

In [66]:
dfdep.rename(columns={'Sim':'dummie_dependentes'})

     dummie_dependentes
0                 False
1                 False
2                  True
3                 False
4                  True
..                  ...
995                True
996               False
997               False
998               False
999               False

[1000 rows x 1 columns]

In [68]:
dfmodel=pd.concat([dfmodel,dfdep],axis=1)

In [70]:
dfmodel.drop(columns=['dependentes'])

,cliente_id,idade,sexo,tempo_contrato_meses,valor_mensal,total_gasto,num_servicos,fatura_online,seguro_dispositivo,suporte_tecnico,churn,DSL,Fibra,Anual,Bianual,Sim
0,C1000,56,Masculino,7,52.52,342.20,1,Não,Não,Sim,Não,0,1,False,False,False
1,C1001,69,Masculino,9,23.93,228.02,2,Sim,Não,Não,Sim,0,1,False,False,False
2,C1002,46,Feminino,48,47.20,2394.83,3,Sim,Não,Não,Não,0,0,False,False,True
3,C1003,32,Masculino,59,20.64,1153.78,1,Não,Sim,Sim,Não,0,0,True,False,False
4,C1004,60,Masculino,39,117.84,4401.51,4,Sim,Não,Não,Sim,0,1,False,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,C1995,18,Masculino,14,112.61,1683.61,4,Sim,Não,Sim,Não,1,0,True,False,True
996,C1996,35,Feminino,34,36.17,1251.98,1,Sim,Sim,Não,Sim,0,1,False,False,False
997,C1997,49,Feminino,53,116.58,5797.98,4,Sim,Sim,Sim,Sim,0,0,False,False,False
998,C1998,64,Masculino,20,40.58,824.77,4,Não,Sim,Não,Não,0,1,False,False,False
999,C1999,66,Feminino,16,94.16,1508.36,2,Sim,Não,Sim,Não,0,1,False,False,False

In [72]:
map_bi = {'Não':0,'Sim':1}

In [74]:
dfmodel.fatura_online = dfmodel.fatura_online.map(map_bi)

In [76]:
dfmodel

,cliente_id,idade,sexo,tempo_contrato_meses,valor_mensal,total_gasto,num_servicos,dependentes,fatura_online,seguro_dispositivo,suporte_tecnico,churn,DSL,Fibra,Anual,Bianual,Sim
0,C1000,56,Masculino,7,52.52,342.20,1,Não,0,Não,Sim,Não,0,1,False,False,False
1,C1001,69,Masculino,9,23.93,228.02,2,Não,1,Não,Não,Sim,0,1,False,False,False
2,C1002,46,Feminino,48,47.20,2394.83,3,Sim,1,Não,Não,Não,0,0,False,False,True
3,C1003,32,Masculino,59,20.64,1153.78,1,Não,0,Sim,Sim,Não,0,0,True,False,False
4,C1004,60,Masculino,39,117.84,4401.51,4,Sim,1,Não,Não,Sim,0,1,False,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,C1995,18,Masculino,14,112.61,1683.61,4,Sim,1,Não,Sim,Não,1,0,True,False,True
996,C1996,35,Feminino,34,36.17,1251.98,1,Não,1,Sim,Não,Sim,0,1,False,False,False
997,C1997,49,Feminino,53,116.58,5797.98,4,Não,1,Sim,Sim,Sim,0,0,False,False,False
998,C1998,64,Masculino,20,40.58,824.77,4,Não,0,Sim,Não,Não,0,1,False,False,False
999,C1999,66,Feminino,16,94.16,1508.36,2,Não,1,Não,Sim,Não,0,1,False,False,False

In [78]:
dfmodel.dependentes = dfmodel.dependentes.map(map_bi)

In [80]:
dfmodel.seguro_dispositivo = dfmodel.seguro_dispositivo.map(map_bi)

In [82]:
dfmodel.suporte_tecnico = dfmodel.suporte_tecnico.map(map_bi)

In [84]:
dfmodel.churn = dfmodel.churn.map(map_bi)

In [86]:
dfmodel = dfmodel.drop(columns={'Sim'})

In [88]:
dfmodel

,cliente_id,idade,sexo,tempo_contrato_meses,valor_mensal,total_gasto,num_servicos,dependentes,fatura_online,seguro_dispositivo,suporte_tecnico,churn,DSL,Fibra,Anual,Bianual
0,C1000,56,Masculino,7,52.52,342.20,1,0,0,0,1,0,0,1,False,False
1,C1001,69,Masculino,9,23.93,228.02,2,0,1,0,0,1,0,1,False,False
2,C1002,46,Feminino,48,47.20,2394.83,3,1,1,0,0,0,0,0,False,False
3,C1003,32,Masculino,59,20.64,1153.78,1,0,0,1,1,0,0,0,True,False
4,C1004,60,Masculino,39,117.84,4401.51,4,1,1,0,0,1,0,1,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,C1995,18,Masculino,14,112.61,1683.61,4,1,1,0,1,0,1,0,True,False
996,C1996,35,Feminino,34,36.17,1251.98,1,0,1,1,0,1,0,1,False,False
997,C1997,49,Feminino,53,116.58,5797.98,4,0,1,1,1,1,0,0,False,False
998,C1998,64,Masculino,20,40.58,824.77,4,0,0,1,0,0,0,1,False,False
999,C1999,66,Feminino,16,94.16,1508.36,2,0,1,0,1,0,0,1,False,False

In [90]:
dfmodel['Anual'] = dfmodel['Anual'].astype(int)

In [92]:
dfmodel['Bianual'] = dfmodel['Bianual'].astype(int)

In [94]:
map_sex = {'Masculino':1,'Feminino':0}

In [96]:
dfmodel.sexo = dfmodel.sexo.map(map_sex)

In [98]:
dfmodel.rename(columns={'sexo': '0=M,1=H'})

,cliente_id,idade,"0=M,1=H",tempo_contrato_meses,valor_mensal,total_gasto,num_servicos,dependentes,fatura_online,seguro_dispositivo,suporte_tecnico,churn,DSL,Fibra,Anual,Bianual
0,C1000,56,1,7,52.52,342.20,1,0,0,0,1,0,0,1,0,0
1,C1001,69,1,9,23.93,228.02,2,0,1,0,0,1,0,1,0,0
2,C1002,46,0,48,47.20,2394.83,3,1,1,0,0,0,0,0,0,0
3,C1003,32,1,59,20.64,1153.78,1,0,0,1,1,0,0,0,1,0
4,C1004,60,1,39,117.84,4401.51,4,1,1,0,0,1,0,1,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,C1995,18,1,14,112.61,1683.61,4,1,1,0,1,0,1,0,1,0
996,C1996,35,0,34,36.17,1251.98,1,0,1,1,0,1,0,1,0,0
997,C1997,49,0,53,116.58,5797.98,4,0,1,1,1,1,0,0,0,0
998,C1998,64,1,20,40.58,824.77,4,0,0,1,0,0,0,1,0,0
999,C1999,66,0,16,94.16,1508.36,2,0,1,0,1,0,0,1,0,0

In [100]:
dfmodel.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 16 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   cliente_id            1000 non-null   object
 1   idade                 1000 non-null   int64
 2   sexo                  1000 non-null   int64
 3   tempo_contrato_meses  1000 non-null   int64
 4   valor_mensal          1000 non-null   float64
 5   total_gasto           1000 non-null   float64
 6   num_servicos          1000 non-null   int64
 7   dependentes           1000 non-null   int64
 8   fatura_online         1000 non-null   int64
 9   seguro_dispositivo    1000 non-null   int64
 10  suporte_tecnico       1000 non-null   int64
 11  churn                 1000 non-null   int64
 12  DSL                   1000 non-null   int32
 13  Fibra                 1000 non-null   int32
 14  Anual                 1000 non-null   int32
 15  Bianual               1000 non-null   int32
dtypes: float64(2), int32(4), int64(9), object(1)
memory usage: 109.5+ KB

In [102]:
dfmodel.corr(numeric_only=True)

,idade,sexo,tempo_contrato_meses,valor_mensal,total_gasto,num_servicos,dependentes,fatura_online,seguro_dispositivo,suporte_tecnico,churn,DSL,Fibra,Anual,Bianual
idade,1.000000,0.036248,0.067661,-0.000694,0.051850,-0.074011,0.003489,0.000169,0.002721,0.020491,-0.011931,-0.034565,0.041832,0.014046,-0.029521
sexo,0.036248,1.000000,-0.010882,-0.020699,-0.023301,0.020594,0.075361,0.000851,-0.056488,0.018287,0.001703,0.000842,0.017285,0.074047,-0.007237
tempo_contrato_meses,0.067661,-0.010882,1.000000,-0.005871,0.758819,0.037041,-0.030652,-0.013167,0.014135,0.009613,0.026780,0.059667,-0.029409,-0.063730,-0.008825
valor_mensal,-0.000694,-0.020699,-0.005871,1.000000,0.552235,-0.011632,0.040001,-0.018831,0.043478,0.026904,0.008616,-0.003847,-0.005276,-0.014928,-0.022917
total_gasto,0.051850,-0.023301,0.758819,0.552235,1.000000,0.004898,-0.013555,-0.025834,0.036169,0.007569,0.026450,0.028221,-0.018494,-0.056920,-0.031106
num_servicos,-0.074011,0.020594,0.037041,-0.011632,0.004898,1.000000,-0.013949,-0.001297,-0.025056,-0.038022,0.026378,0.085888,-0.069166,-0.053840,0.035558
dependentes,0.003489,0.075361,-0.030652,0.040001,-0.013555,-0.013949,1.000000,-0.000386,-0.012171,-0.028522,0.077365,0.049949,-0.038838,0.056030,-0.001467
fatura_online,0.000169,0.000851,-0.013167,-0.018831,-0.025834,-0.001297,-0.000386,1.000000,-0.007004,-0.011886,-0.038501,0.005479,-0.009565,-0.027220,-0.057445
seguro_dispositivo,0.002721,-0.056488,0.014135,0.043478,0.036169,-0.025056,-0.012171,-0.007004,1.000000,-0.091483,-0.034197,-0.011023,-0.007150,0.017415,-0.034604
suporte_tecnico,0.020491,0.018287,0.009613,0.026904,0.007569,-0.038022,-0.028522,-0.011886,-0.091483,1.000000,0.037942,0.052351,-0.023114,0.032645,-0.004221
churn,-0.011931,0.001703,0.026780,0.008616,0.026450,0.026378,0.077365,-0.038501,-0.034197,0.037942,1.000000,-0.016422,-0.012865,-0.050942,0.059646
DSL,-0.034565,0.000842,0.059667,-0.003847,0.028221,0.085888,0.049949,0.005479,-0.011023,0.052351,-0.016422,1.000000,-0.658884,0.019623,-0.000371
Fibra,0.041832,0.017285,-0.029409,-0.005276,-0.018494,-0.069166,-0.038838,-0.009565,-0.007150,-0.023114,-0.012865,-0.658884,1.000000,0.004144,-0.012031
Anual,0.014046,0.074047,-0.063730,-0.014928,-0.056920,-0.053840,0.056030,-0.027220,0.017415,0.032645,-0.050942,0.019623,0.004144,1.000000,-0.211623
Bianual,-0.029521,-0.007237,-0.008825,-0.022917,-0.031106,0.035558,-0.001467,-0.057445,-0.034604,-0.004221,0.059646,-0.000371,-0.012031,-0.211623,1.000000

In [104]:
dfmodel = dfmodel.drop(columns={'cliente_id'})

In [106]:
dfchurn = df['churn'].reset_index()

In [108]:
dfmodel = dfmodel.drop(columns={'churn'})

In [110]:
dfchurn

     index churn
0        0   Não
1        1   Sim
2        2   Não
3        3   Não
4        4   Sim
..     ...   ...
995    995   Não
996    996   Sim
997    997   Sim
998    998   Não
999    999   Não

[1000 rows x 2 columns]

In [112]:
dfmodel = pd.concat([dfmodel,dfchurn['churn']],axis=1)

In [114]:
dfmodel.churn = dfmodel.churn.map(map_bi)

In [116]:
dfmodel

,idade,sexo,tempo_contrato_meses,valor_mensal,total_gasto,num_servicos,dependentes,fatura_online,seguro_dispositivo,suporte_tecnico,DSL,Fibra,Anual,Bianual,churn
0,56,1,7,52.52,342.20,1,0,0,0,1,0,1,0,0,0
1,69,1,9,23.93,228.02,2,0,1,0,0,0,1,0,0,1
2,46,0,48,47.20,2394.83,3,1,1,0,0,0,0,0,0,0
3,32,1,59,20.64,1153.78,1,0,0,1,1,0,0,1,0,0
4,60,1,39,117.84,4401.51,4,1,1,0,0,0,1,0,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,18,1,14,112.61,1683.61,4,1,1,0,1,1,0,1,0,0
996,35,0,34,36.17,1251.98,1,0,1,1,0,0,1,0,0,1
997,49,0,53,116.58,5797.98,4,0,1,1,1,0,0,0,0,1
998,64,1,20,40.58,824.77,4,0,0,1,0,0,1,0,0,0
999,66,0,16,94.16,1508.36,2,0,1,0,1,0,1,0,0,0

### Data Processed

## Preditive modeling:

* Wich Machine Learning algorithm (Logistic Regression, Random Forest, XGBoost) better perform performe?

In [123]:
X = dfmodel.drop(columns={'churn'})

In [125]:
X

,idade,sexo,tempo_contrato_meses,valor_mensal,total_gasto,num_servicos,dependentes,fatura_online,seguro_dispositivo,suporte_tecnico,DSL,Fibra,Anual,Bianual
0,56,1,7,52.52,342.20,1,0,0,0,1,0,1,0,0
1,69,1,9,23.93,228.02,2,0,1,0,0,0,1,0,0
2,46,0,48,47.20,2394.83,3,1,1,0,0,0,0,0,0
3,32,1,59,20.64,1153.78,1,0,0,1,1,0,0,1,0
4,60,1,39,117.84,4401.51,4,1,1,0,0,0,1,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,18,1,14,112.61,1683.61,4,1,1,0,1,1,0,1,0
996,35,0,34,36.17,1251.98,1,0,1,1,0,0,1,0,0
997,49,0,53,116.58,5797.98,4,0,1,1,1,0,0,0,0
998,64,1,20,40.58,824.77,4,0,0,1,0,0,1,0,0
999,66,0,16,94.16,1508.36,2,0,1,0,1,0,1,0,0

In [127]:
y=dfmodel['churn'].reset_index()

In [129]:
y.reset_index(inplace=True)

In [131]:
y=y.drop(columns={'level_0','index'})

In [133]:
from sklearn.model_selection import train_test_split

### 25% of data for test

In [179]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, 
    test_size=0.25, 
    random_state=42,
    stratify=y
   )
print('Treino',round(y_train.mean().mul(100),2))
print('Teste',round(y_test.mean().mul(100),2))

Treino churn    30.93
dtype: float64
Teste churn    30.8
dtype: float64

In [181]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [183]:
print("\nShape dos dados:")
print(f"X_train: {X_train.shape} | y_train: {y_train.shape}")
print(f"X_test:  {X_test.shape}  | y_test:  {y_test.shape}")

print("\nExemplo de X_train:")
print(X_train.head(3))

Shape dos dados:
X_train: (750, 14) | y_train: (750, 1)
X_test:  (250, 14)  | y_test:  (250, 1)

Exemplo de X_train:
     idade  sexo  tempo_contrato_meses  valor_mensal  total_gasto  \
632     54     1                    25         71.81      1865.49
553     75     0                    36        119.65      4294.80
620     33     0                    33         38.08      1134.87

     num_servicos  dependentes  fatura_online  seguro_dispositivo  \
632             3            1              1                   1
553             1            0              0                   1
620             4            1              1                   0

     suporte_tecnico  DSL  Fibra  Anual  Bianual
632                1    1      0      1        0
553                0    1      0      1        0
620                0    0      0      0        0

### Precision Rate

In [186]:
from xgboost import XGBClassifier
from sklearn.metrics import classification_report

# Treinar modelo
model = XGBClassifier(
    scale_pos_weight=(len(y_train.churn) - sum(y_train.churn)) / sum(y_train.churn),  # Balanceamento
    eval_metric='aucpr',
    random_state=42
)
model.fit(X_train_scaled, y_train)

# Avaliar
y_pred = model.predict(X_test_scaled)
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.69      0.72      0.70       173
           1       0.30      0.27      0.29        77

    accuracy                           0.58       250
   macro avg       0.49      0.49      0.49       250
weighted avg       0.57      0.58      0.57       250

### Bad precision Model

### Made some changes, but still not good enough

In [190]:

model = XGBClassifier(scale_pos_weight=180/70, eval_metric='aucpr')
#model = XGBClassifier(
    #scale_pos_weight=(len(y_train.churn) - sum(y_train.churn)) / sum(y_train.churn),  # Balanceamento
    #eval_metric='aucpr',
    #random_state=42
#)
model.fit(X_train_scaled, y_train)

# Avaliar
y_pred = model.predict(X_test_scaled)
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.69      0.74      0.71       173
           1       0.30      0.25      0.27        77

    accuracy                           0.59       250
   macro avg       0.49      0.49      0.49       250
weighted avg       0.57      0.59      0.58       250

In [192]:
from sklearn.model_selection import GridSearchCV
param_grid = {
    'max_depth': [3, 5],
    'learning_rate': [0.01, 0.1],
    'subsample': [0.8, 1.0]
}
grid = GridSearchCV(XGBClassifier(), param_grid, scoring='f1')
grid.fit(X_train, y_train)

GridSearchCV(estimator=XGBClassifier(base_score=None, booster=None,
                                     callbacks=None, colsample_bylevel=None,
                                     colsample_bynode=None,
                                     colsample_bytree=None, device=None,
                                     early_stopping_rounds=None,
                                     enable_categorical=False, eval_metric=None,
                                     feature_types=None, gamma=None,
                                     grow_policy=None, importance_type=None,
                                     interaction_constraints=None,
                                     learning_rate=None, max_b...one,
                                     max_cat_threshold=None,
                                     max_cat_to_onehot=None,
                                     max_delta_step=None, max_depth=None,
                                     max_leaves=None, min_child_weight=None,
                                     missing=nan, monotone_constraints=None,
                                     multi_strategy=None, n_estimators=None,
                                     n_jobs=None, num_parallel_tree=None,
                                     random_state=None, ...),
             param_grid={'learning_rate': [0.01, 0.1], 'max_depth': [3, 5],
                         'subsample': [0.8, 1.0]},
             scoring='f1')

In [193]:
model = XGBClassifier(scale_pos_weight=125/125, eval_metric='aucpr')
model.fit(X_train_scaled, y_train)

y_pred = model.predict(X_test_scaled)
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.69      0.77      0.73       173
           1       0.32      0.23      0.27        77

    accuracy                           0.61       250
   macro avg       0.51      0.50      0.50       250
weighted avg       0.58      0.61      0.59       250

In [194]:
model = XGBClassifier(
    scale_pos_weight=(len(y_train.churn) - sum(y_train.churn)) / sum(y_train.churn),  # Balanceamento
    eval_metric='aucpr',
    random_state=42)
model.fit(X_train_scaled, y_train)

y_pred = model.predict(X_test_scaled)
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.69      0.72      0.70       173
           1       0.30      0.27      0.29        77

    accuracy                           0.58       250
   macro avg       0.49      0.49      0.49       250
weighted avg       0.57      0.58      0.57       250

### Back to old model, but still not good enough.

### Gonna need more Data to raise precision on Churn prediction.